version: "3"

services: 
  node-docker: 
    build: 
      context: .
      args: 
        NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo: 
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=root
     - NODE_ENV=development
     - MONGO_IP=mongo
     - MONGO_PORT=27017
     - MONGO_USER=root
     - MONGO_PASS=root
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
   