version: "3"

services: 
  node-docker: 
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - .:/app:ro
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=root
      